name: Run CATS
on:
  push:
    branches:
    - run-cats
  workflow_dispatch:
    inputs:
      pool-name:
        type: string
      pool-namespace:
        type: string

jobs:
  run-cats:
    env:
      POOL_NAME: "${{ inputs.pool-name || vars.SHEPHERD_POOL_NAME }}"
      POOL_NAMESPACE: "${{ inputs.pool-namespace|| 'official'}}"
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    container: us-west2-docker.pkg.dev/shepherd-268822/shepherd2/concourse-resource:latest
    steps:
    - name: Checkout cf-cli
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/cli
        ref: ${{github.event.workflow_run.head_sha}}

    - name: Checkout cli-ci
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/cli-ci
        path: cli-ci

    - name: Checkout cf-acceptance-tests
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/cf-acceptance-tests
        ref: release-candidate
        path: cf-acceptance-tests

    - name: Checkout cf-deployment
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/cf-deployment
        path: cf-deployment

    - name: Checkout CF deployment tasks
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/cf-deployment-concourse-tasks
        path: cf-deployment-concourse-tasks

    - id: claim-env
      if: ${{ false }}
      name: Claim Environment
      env:
        account_token: ${{ secrets.SHEPHERD_SERVICE_ACCOUNT_TOKEN }}
      run: |
        shepherd login service-account ${account_token}

        echo "shepherd create lease --duration 8h --pool ${POOL_NAME} --pool-namespace ${POOL_NAMESPACE} --namespace tas-devex"
        lease_id=$(shepherd create lease --duration 8h --pool ${POOL_NAME} --pool-namespace ${POOL_NAMESPACE} --namespace tas-devex --json | jq -r .id)
        # Give sometime for the lease to complete. Shepherd may take upto an 3 hours to create an env
        # if the pool is empty.
        count=0
        while [ $count -lt 360 ] ; do
          sleep 30
          status=$(shepherd get lease ${lease_id} --namespace tas-devex --json | jq -r .status)
          if [ $status == "LEASED" ] ; then
            shepherd get lease ${lease_id} --namespace tas-devex --json | jq .output > metadata.json
            break
          elif [ $status == "FAILED" -o $status == "EXPIRED" ] ; then
            echo "There was an error obtaining the lease. Lease status is ${status}."
            exit 1
          else
            echo "Waiting for environment to be ready. Lease status is ${status}."
          fi
          count=$(($count+1))
        done

        env_name=$(jq -r .name metadata.json)
        cat metadata.json | jq -r '.name'
        echo "lease-id=$lease_id" >> "${GITHUB_OUTPUT}"

    - name: Reuse previous claim
      env:
        account_token: ${{ secrets.SHEPHERD_SERVICE_ACCOUNT_TOKEN }}
        lease_id: ${{ vars.LEASE_ID}}
      run: |
        shepherd login service-account ${account_token}
        shepherd get lease ${lease_id} --namespace tas-devex --json | jq .output > metadata.json

        cat metadata.json | jq -r '.name'
        echo "lease-id=$lease_id" >> "${GITHUB_OUTPUT}"

    - name: Set Up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Install Tools
      run: |
        go version

        install_location=/usr/local/bin
        bbl_artifact=bbl-v8.4.110_linux_x86-64
        bosh_cli_artifact=bosh-cli-7.0.1-linux-amd64
        credhub_artifact=credhub-linux-2.9.4.tgz
        curl https://github.com/cloudfoundry/bosh-bootloader/releases/download/v8.4.110/${bbl_artifact} --silent --location --output  $install_location/bbl
        chmod +x $install_location/bbl
        bbl --version

        curl https://s3.amazonaws.com/bosh-cli-artifacts/$bosh_cli_artifact --silent --output $install_location/bosh --location
        chmod +x $install_location/bosh
        bosh --version

        curl https://github.com/cloudfoundry/credhub-cli/releases/download/2.9.4/$credhub_artifact --silent --output /tmp/$credhub_artifact --location
        tar xzvf /tmp/$credhub_artifact
        mv credhub $install_location/credhub
        chmod +x $install_location/credhub
        credhub --version

        curl -L https://github.com/pivotal-cf/om/releases/download/7.13.0/om-linux-amd64-7.13.0 --output $install_location/om
        chmod +x $install_location/om

        apt-get update
        apt-get install -y build-essential unzip

    - name: Upload latest CAPI release
      run: |
        capi_release_version=$(curl -s https://api.github.com/repos/cloudfoundry/capi-release/releases/latest | jq -r .tag_name)
        echo "Latest CAPI release is $capi_release_version"
        
        export OM_TARGET="$(cat metadata.json | jq -r .ops_manager.url)"
        export OM_USERNAME="$(cat metadata.json | jq -r .ops_manager.username)"
        export OM_PASSWORD="$(cat metadata.json | jq -r .ops_manager.password)"
        eval "$(om bosh-env)"

        env_name=$(jq -r .name metadata.json)
        jq -r .ops_manager_private_key metadata.json > /tmp/${env_name}.private
        jumpbox_ip=$(jq -r .ops_manager_public_ip metadata.json)
        export BOSH_ALL_PROXY="ssh+socks5://ubuntu@${jumpbox_ip}:22?private-key=/tmp/${env_name}.private"

        bosh upload-release "https://bosh.io/d/github.com/cloudfoundry/capi-release?v=$capi_release_version"


    - name: Deploy Isolation Segment and OIDC Provider
      run: |
        export OM_TARGET="$(cat metadata.json | jq -r .ops_manager.url)"
        export OM_USERNAME="$(cat metadata.json | jq -r .ops_manager.username)"
        export OM_PASSWORD="$(cat metadata.json | jq -r .ops_manager.password)"
        eval "$(om bosh-env)"

        env_name=$(jq -r .name metadata.json)
        jq -r .ops_manager_private_key metadata.json > /tmp/${env_name}.private
        jumpbox_ip=$(jq -r .ops_manager_public_ip metadata.json)
        export BOSH_ALL_PROXY="ssh+socks5://ubuntu@${jumpbox_ip}:22?private-key=/tmp/${env_name}.private"

        cf_deployment=$(bosh ds --json | jq -r '.Tables[] | select(.Content | startswith("deploy")).Rows[] | select(.name | startswith("cf")) | .name')

        # deploy
        bosh -d ${cf_deployment} manifest > /tmp/manifest.yml
        bosh interpolate /tmp/manifest.yml \
          -o .github/ops-files/use-cflinuxfs3.yml \
          -o .github/ops-files/replace-redis.yml \
          -o cf-deployment/operations/use-internal-lookup-for-route-services.yml \
          -o cf-deployment/operations/add-persistent-isolation-segment-diego-cell.yml \
          -o cli-ci/ci/infrastructure/operations/use-latest-capi.yml \
          -o cli-ci/ci/infrastructure/operations/add-oidc-provider.yml \
          -o cli-ci/ci/infrastructure/operations/add-uaa-client-credentials.yml \
          -o cli-ci/ci/infrastructure/operations/diego-cell-instances.yml \
          -v client-secret="${{ secrets.CLIENT_SECRET }}" \
          > ./director.yml

        bosh -d ${cf_deployment} deploy director.yml -n
        echo "Deployed CAPI version:"
        bosh -d ${cf_deployment} releases | grep capi

    - name: Add CATS config
      run: |
        set -eu

        ENV=$(jq -r .name metadata.json)
        API="$(jq -r .cf.api_url metadata.json)"
        DOMAIN=$(echo $API | sed "s/^api\.//")
        CF_INT_USERNAME="admin"

        export OM_TARGET="$(cat metadata.json | jq -r .ops_manager.url)"
        export OM_USERNAME="$(cat metadata.json | jq -r .ops_manager.username)"
        export OM_PASSWORD="$(cat metadata.json | jq -r .ops_manager.password)"
        eval "$(om bosh-env)"

        env_name=$(jq -r .name metadata.json)
        jq -r .ops_manager_private_key metadata.json > /tmp/${env_name}.private
        jumpbox_ip=$(jq -r .ops_manager_public_ip metadata.json)
        export BOSH_ALL_PROXY="ssh+socks5://ubuntu@${jumpbox_ip}:22?private-key=/tmp/${env_name}.private"

        credhub login
        CF_INT_PASSWORD=$(credhub get -n /bosh-$ENV/cf/cf_admin_password | bosh interpolate --path /value -)

        cat << EOF | jq -S . > cats_config.json
        {
          "admin_password": "${CF_INT_PASSWORD}",
          "admin_user": "${CF_INT_USERNAME}",
          "api": "${API}",
          "apps_domain": "${DOMAIN}",
          "backend" : "diego",
          "broker_start_timeout": 330,
          "cf_push_timeout": 210,
          "default_timeout": 120,
          "long_curl_timeout": 210,
          "skip_ssl_validation": true,
          "use_http": true,
          "include_apps": true,
          "include_backend_compatibility": false,
          "include_container_networking": true,
          "include_detect": true,
          "include_docker": true,
          "include_internet_dependent": true,
          "include_isolation_segments": true,
          "isolation_segment_name": "persistent_isolation_segment",
          "include_private_docker_registry": false,
          "include_route_services": true,
          "include_routing": true,
          "include_routing_isolation_segments": false,
          "include_security_groups": true,
          "include_services": true,
          "include_service_discovery": true,
          "include_service_instance_sharing": true,
          "include_ssh": true,
          "include_sso": false,
          "include_tasks": true,
          "include_tcp_routing": true,
          "include_v3": true,
          "include_zipkin": true
        }
        EOF

        make build
        echo "$PWD/out" >> $GITHUB_PATH
        export PATH="$PWD/out:$PATH"
        cf version

        export CF_USERNAME=${CF_INT_USERNAME}
        export CF_PASSWORD=${CF_INT_PASSWORD}
        cf api ${API} --skip-ssl-validation
        cf auth
        cf enable-feature-flag diego_docker
        cf enable-feature-flag service_instance_sharing

    - name: Run CATS Tests
      run: |
        set -xeu

        export CONFIG
        CONFIG=$(mktemp)

        original_config="${PWD}/cats_config.json"
        cp ${original_config} ${CONFIG}

        cd ./cf-acceptance-tests
        export CF_DIAL_TIMEOUT=11
        export CF_PLUGIN_HOME=$HOME
        go version

        ./bin/test \
          --keep-going \
          --randomize-all \
          --skip-package=helpers \
          --nodes="12" \
          --flake-attempts=2 \
          --timeout="2h" \
          --no-color

