# Workflow to trigger building docs in CAPI Release
# so we pick up changes to docs
# inspired by: https://medium.com/hostspaceng/triggering-workflows-in-another-repository-with-github-actions-4f581f8e0ceb
# docs: https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event

name: Trigger CAPI Release docs workflow

on:
  # TODO add correct trigger on tags / releases
  push:
    branches:
    - main
    - trigger-docs
  # allow manual run
  workflow_dispatch:

jobs:
  trigger-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger v2 docs build
        run: |
          # Set the required variables
          target_repo="pivotalgeorge/capi-release"
          target_ref="gh-pages-v2-docs"
          target_workflow="gh_pages_docs_v2.yml"
  
          # show any error and exit nonzero
          curl --silent --fail-with-body --show-error -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CCNG_USER_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${target_repo}/actions/workflows/${target_workflow}/dispatches \
            -d "{\"ref\": \"${target_ref}\"}"
